spring.datasource.url=jdbc:postgresql://ider-database.westeurope.cloudapp.azure.com:5433/h674545
spring.datasource.username=h674545
spring.datasource.password=Saturn120536!

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.application.name=oblig4-del1

# Her gir vi beskjed til ViewResolver hvordan view-navn mappes til
# konkret filnavn. Eks: "hilsen" -> src/main/webapp /WEB-INF/hilsen.jsp
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

server.port=8085